export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_NOTIFICATION_EVENT = 'SET_NOTIFICATION_EVENT';
export const SET_CHALLENGE_TAB = 'SET_CHALLENGE_TAB';
export const DO_NOT_SHOW_WIZARD = 'DO_NOT_SHOW_WIZARD';
